### ISSUE TITLE
Roadmap and incubation

### ISSUE THREAD

**Issue by acm19** [spring-cloud-incubator/spring-cloud-sleuth-otel#74] opened 2021-08-19 12:24 UTC
We are looking into using this project and have a few question we couldn't find documented anywhere:

* What does it mean the project is incubating (`spring-cloud-incubator`)? What are the limitations of such a project?
* Is there a roadmap for it to become part of "normal" Spring Cloud?
* Do you recommend using it as it is in production environments?

**Comment by marcingrzejszczak** [comment] 2021-08-19 14:06
That's a duplicate of https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/issues/56

> Do you recommend using it as it is in production environments?

I would personally have my doubts to use an alpha OTel Java Instrumentation.

**Closed by marcingrzejszczak** 2021-08-19 14:06 UTC
